### PR TITLE
Exit with code 1 on error

### LINKED ISSUE #41: Use `sys.exit(1)` on error
Unless I'm missing something, I think you should use `sys.exit(1)` instead of `sys.exit()` (with an implicit exit code of `0`) whenever the program exists abnormally (i.e. with an error).

This would be especially helpful in custom scripts around `passhole`.

In the meantime, I resolved to parsing the output, but it feels kinda dirty/hacky.

Thoughts?

### PR DESCRIPTION
**Pull request by ulken**
I simply replaced all occurrences of `sys.exit()` with `sys.exit(1)`. I went through all of them before committing and found it reasonable. All explicit exits (in contrast to when normal execution of the program is done) indicate something unexpected has happened.

I wasn't able to actually run the program. How do I do that? I tried running the main Python file but it complains about relative import of `version` in a non-package. Tried using `-m` and specifying the package/module name but never found the right combo.

Closes #41

### CODE REVIEW

**Comment by Evidlo** [comment]
pip should put both `ph` and `passhole` in your PATH.  You should be able to run those commands directly.

**Comment by ulken** [comment]
> pip should put both `ph` and `passhole` in your PATH.  You should be able to execute those commands directly.

Oh, wow. So it overwrites the bins installed from the registry? Interesting.

**Comment by Evidlo** [comment]
> Oh, wow. So it overwrites the bins installed from the registry? Interesting.

You mean the system binaries in /usr/local?  Yes its possible that pip can overwrite them.  That's why its recommended to generally use `--user` when installing with pip or use a virtualenv.

**Comment by ulken** [comment]
Alright, cool. Thanks!

**Pull request merged**
